//  Copyright © 2026 Stezza @ inc. Licensed under the Thou Shalt Not Profit License version 1.0.
//  See LICENSE for details.
//
//  AppleIntelParams.hpp — typed mirror of Apple's framebuffer-driver parameter
//  structures. AUTO-GENERATED by tools/extract_apple_params.py from a Ghidra-
//  analyzed AppleIntelTGLGraphicsFramebuffer.kext. Do not edit by hand — re-run
//  the script after updating struct definitions in Ghidra.
//
//  Source program: AppleIntelTGLGraphicsFramebuffer (via Ghidra-verified offsets)
//  Generated: 2026-05-11T15:44 (verified against paramsSurfCompare + setupPipeScaler disasm)

#ifndef AppleIntelParams_hpp
#define AppleIntelParams_hpp

#include <stdint.h>

namespace AppleIntel {

// ---- Structs (fields identified) ----

// struct CRTCParams -- 0xF0 bytes, 33 components
// Verified offset sources:
//   +0x00..+0x2C  friend's Ghidra screenshot
//   +0x48..+0x54  setupPipeScaler disasm (IntelLog format strings)
//   +0x88..+0xB4  setupDSCEngineParams PPS_* writes
//   +0xE8/+0xEC   setupDSCEngineParams DSC engine + joiner writes
struct CRTCParams {
    uint32_t       TRANS_CLK_SEL;        // +0x0
    uint32_t       TRANS_DDI_FUNC_CTL;   // +0x4
    uint32_t       TRANS_DDI_FUNC_CTL2;  // +0x8
    uint32_t       TRANS_MSA_MISC;       // +0xC
    uint32_t       TRANS_HTOTAL;         // +0x10
    uint32_t       TRANS_HBLANK;         // +0x14
    uint32_t       TRANS_HSYNC;          // +0x18
    uint32_t       TRANS_VTOTAL;         // +0x1C
    uint32_t       TRANS_VBLANK;         // +0x20
    uint32_t       TRANS_VSYNC;          // +0x24
    uint32_t       PIPE_SRCSZ;           // +0x28
    uint32_t       TRANS_CONF;           // +0x2C
    uint8_t        _pad_0030[24];        // +0x30..+0x47  TBD
    uint32_t       PS_PS_WIN_POS;        // +0x48  pipe scaler window position
    uint32_t       PS_PS_WIN_SZ;         // +0x4C  pipe scaler window size — DOWNSCALE SUSPECT
    uint32_t       PIPE_SEAM_EXCESS;     // +0x50  dual-pipe seam join offset
    uint32_t       PS_HPHASE;            // +0x54  horizontal phase
    uint8_t        _pad_0058[48];        // +0x58..+0x87  TBD
    uint32_t       PPS_0;                // +0x88
    uint32_t       PPS_1;                // +0x8C
    uint32_t       PPS_2;                // +0x90
    uint32_t       PPS_3;                // +0x94
    uint32_t       PPS_4;                // +0x98
    uint32_t       PPS_5;                // +0x9C
    uint32_t       PPS_6;                // +0xA0
    uint32_t       PPS_7;                // +0xA4
    uint32_t       PPS_8;                // +0xA8
    uint32_t       PPS_9;                // +0xAC
    uint32_t       PPS_10;               // +0xB0
    uint32_t       PPS_16;               // +0xB4
    uint8_t        _pad_00B8[48];        // +0xB8..+0xE7  TBD: DSC slice/bpp/line buffer
    uint32_t       DSC_ENGINE_SEL;       // +0xE8
    uint32_t       DSC_JOINER_CTL;       // +0xEC
};
static_assert(sizeof(CRTCParams) == 0xF0, "CRTCParams size");
static_assert(__builtin_offsetof(CRTCParams, TRANS_CLK_SEL) == 0x0, "CRTCParams.TRANS_CLK_SEL");
static_assert(__builtin_offsetof(CRTCParams, TRANS_DDI_FUNC_CTL) == 0x4, "CRTCParams.TRANS_DDI_FUNC_CTL");
static_assert(__builtin_offsetof(CRTCParams, TRANS_DDI_FUNC_CTL2) == 0x8, "CRTCParams.TRANS_DDI_FUNC_CTL2");
static_assert(__builtin_offsetof(CRTCParams, TRANS_MSA_MISC) == 0xC, "CRTCParams.TRANS_MSA_MISC");
static_assert(__builtin_offsetof(CRTCParams, TRANS_HTOTAL) == 0x10, "CRTCParams.TRANS_HTOTAL");
static_assert(__builtin_offsetof(CRTCParams, TRANS_HBLANK) == 0x14, "CRTCParams.TRANS_HBLANK");
static_assert(__builtin_offsetof(CRTCParams, TRANS_HSYNC) == 0x18, "CRTCParams.TRANS_HSYNC");
static_assert(__builtin_offsetof(CRTCParams, TRANS_VTOTAL) == 0x1C, "CRTCParams.TRANS_VTOTAL");
static_assert(__builtin_offsetof(CRTCParams, TRANS_VBLANK) == 0x20, "CRTCParams.TRANS_VBLANK");
static_assert(__builtin_offsetof(CRTCParams, TRANS_VSYNC) == 0x24, "CRTCParams.TRANS_VSYNC");
static_assert(__builtin_offsetof(CRTCParams, PIPE_SRCSZ) == 0x28, "CRTCParams.PIPE_SRCSZ");
static_assert(__builtin_offsetof(CRTCParams, TRANS_CONF) == 0x2C, "CRTCParams.TRANS_CONF");
static_assert(__builtin_offsetof(CRTCParams, PS_PS_WIN_POS) == 0x48, "CRTCParams.PS_PS_WIN_POS");
static_assert(__builtin_offsetof(CRTCParams, PS_PS_WIN_SZ) == 0x4C, "CRTCParams.PS_PS_WIN_SZ");
static_assert(__builtin_offsetof(CRTCParams, PIPE_SEAM_EXCESS) == 0x50, "CRTCParams.PIPE_SEAM_EXCESS");
static_assert(__builtin_offsetof(CRTCParams, PS_HPHASE) == 0x54, "CRTCParams.PS_HPHASE");
static_assert(__builtin_offsetof(CRTCParams, PPS_0) == 0x88, "CRTCParams.PPS_0");
static_assert(__builtin_offsetof(CRTCParams, PPS_1) == 0x8C, "CRTCParams.PPS_1");
static_assert(__builtin_offsetof(CRTCParams, PPS_2) == 0x90, "CRTCParams.PPS_2");
static_assert(__builtin_offsetof(CRTCParams, PPS_3) == 0x94, "CRTCParams.PPS_3");
static_assert(__builtin_offsetof(CRTCParams, PPS_4) == 0x98, "CRTCParams.PPS_4");
static_assert(__builtin_offsetof(CRTCParams, PPS_5) == 0x9C, "CRTCParams.PPS_5");
static_assert(__builtin_offsetof(CRTCParams, PPS_6) == 0xA0, "CRTCParams.PPS_6");
static_assert(__builtin_offsetof(CRTCParams, PPS_7) == 0xA4, "CRTCParams.PPS_7");
static_assert(__builtin_offsetof(CRTCParams, PPS_8) == 0xA8, "CRTCParams.PPS_8");
static_assert(__builtin_offsetof(CRTCParams, PPS_9) == 0xAC, "CRTCParams.PPS_9");
static_assert(__builtin_offsetof(CRTCParams, PPS_10) == 0xB0, "CRTCParams.PPS_10");
static_assert(__builtin_offsetof(CRTCParams, PPS_16) == 0xB4, "CRTCParams.PPS_16");
static_assert(__builtin_offsetof(CRTCParams, DSC_ENGINE_SEL) == 0xE8, "CRTCParams.DSC_ENGINE_SEL");
static_assert(__builtin_offsetof(CRTCParams, DSC_JOINER_CTL) == 0xEC, "CRTCParams.DSC_JOINER_CTL");

// struct PLANEPARAMS -- 0x2C bytes, 5 verified fields
// Verified from paramsSurfCompare disasm (3 offsets accessed) +
// DIAG dump (2 additional live fields discovered in declared padding):
//   [+0x00] PLANE_CTL    — tiling bits[12:10]: 0=linear, 1=X-tile, 4=Tile4; pixel fmt bits[27:23]
//   [+0x04] unk_0004     — static config word; observed 0x2000 (bit 13) on both pl1/pl2
//   [+0x18] PLANE_STRIDE
//   [+0x1C] PLANE_SIZE   — plane dimensions: bits[31:16]=(height-1), bits[15:0]=(width-1)
//                          observed 0x063f09ff = 1599<<16|2559 for 2560x1600
//                          NOTE: reversed half-word order vs CRTCParams.PIPE_SRCSZ
//   [+0x20] PLANE_SURF
struct PLANEPARAMS {
    uint32_t       PLANE_CTL;            // +0x00
    uint32_t       unk_0004;             // +0x04  static config; observed 0x2000 (bit 13)
    uint8_t        _pad_0008[16];        // +0x08..+0x17  TBD
    uint32_t       PLANE_STRIDE;         // +0x18
    uint32_t       PLANE_SIZE;           // +0x1C  (height-1)<<16 | (width-1)
    uint32_t       PLANE_SURF;           // +0x20
    uint8_t        _pad_0024[8];         // +0x24..+0x2B  TBD
};
static_assert(sizeof(PLANEPARAMS) == 0x2C, "PLANEPARAMS size");
static_assert(__builtin_offsetof(PLANEPARAMS, PLANE_CTL)    == 0x00, "PLANEPARAMS.PLANE_CTL");
static_assert(__builtin_offsetof(PLANEPARAMS, unk_0004)     == 0x04, "PLANEPARAMS.unk_0004");
static_assert(__builtin_offsetof(PLANEPARAMS, PLANE_STRIDE) == 0x18, "PLANEPARAMS.PLANE_STRIDE");
static_assert(__builtin_offsetof(PLANEPARAMS, PLANE_SIZE)   == 0x1C, "PLANEPARAMS.PLANE_SIZE");
static_assert(__builtin_offsetof(PLANEPARAMS, PLANE_SURF)   == 0x20, "PLANEPARAMS.PLANE_SURF");

// struct SCALERPARAMS -- 0xC bytes
// Per-plane scaler (NOT the pipe scaler — pipe scaler params live in CRTCParams
// at +0x48..+0x54). Use this for per-plane setupScaler calls if/when wired.
struct SCALERPARAMS {
    uint32_t       PS_CTRL;              // +0x0
    uint32_t       PS_WIN_POS;           // +0x4
    uint32_t       PS_WIN_SZ;            // +0x8
};
static_assert(sizeof(SCALERPARAMS) == 0xC, "SCALERPARAMS size");
static_assert(__builtin_offsetof(SCALERPARAMS, PS_CTRL) == 0x0, "SCALERPARAMS.PS_CTRL");
static_assert(__builtin_offsetof(SCALERPARAMS, PS_WIN_POS) == 0x4, "SCALERPARAMS.PS_WIN_POS");
static_assert(__builtin_offsetof(SCALERPARAMS, PS_WIN_SZ) == 0x8, "SCALERPARAMS.PS_WIN_SZ");

// struct ppsOpt_t -- 0x50 bytes (opaque; size from memset in setupDSCEngineParams)
struct ppsOpt_t {
    uint8_t        _opaque[80];          // +0x0
};
static_assert(sizeof(ppsOpt_t) == 0x50, "ppsOpt_t size");

// struct ppsConfig_t -- 0x18C bytes (opaque; size from memset in setupDSCEngineParams)
struct ppsConfig_t {
    uint8_t        _opaque[396];         // +0x0
};
static_assert(sizeof(ppsConfig_t) == 0x18C, "ppsConfig_t size");

// ---- Structs (PCode-promoted, fully named) ----

// struct AppleIntelMMIO — minimal accessor-backed layout.
// getMMIOBase/setMMIOBase imply a base-pointer ivar even when nested PCode does
// not recover deeper fields from the pointee object.
struct AppleIntelMMIO {
    volatile uint8_t *fMMIOBase;                   // +0x00 [KNOWN] MMIO base pointer
};
static_assert(__builtin_offsetof(AppleIntelMMIO, fMMIOBase) == 0x00, "AppleIntelMMIO.fMMIOBase");

struct AppleIntelBaseController; // forward — needed by AppleIntelPlaneRegCache below

// struct AppleIntelPlaneRegCache — object pointed to by AppleIntelPlane::fRegCache (+0x88).
//
// WARNING: PLANE_CTL/PLANE_STRIDE/PLANE_COLOR_CTL at +0x100/+0x104/+0x154 are INLINE
// fields of AppleIntelPlane itself (verified from init + configurePlane disasm).
// fRegCache points to a register write accessor (DSB channel); its internal layout is
// UNVERIFIED. Do NOT use this struct to read/write PLANE_CTL — use getMember on the plane.
// struct AppleIntelPlaneRegCache — DSB-based accessor committed atomically per frame.
// Carries BOTH plane registers and seam-scaler (scaler 2) registers — Apple programs them
// together so the seam-join settings track every plane update.
// Verified from DIAG[PlaneRegCache] raw dump at enablePlane time.
struct AppleIntelPlaneRegCache {
    void                    *_vtable;              // +0x00  C++ vtable
    uint8_t                  _pad_0008[0x8];       // +0x08  OSObject retain count etc.
    AppleIntelBaseController *fController;         // +0x10  [VERIFIED] controller back-ptr
    uint8_t                  _pad_0018[0x8];       // +0x18..+0x1F  unknown (indices?)
    uint32_t                 unk_0020;             // +0x20  observed 0x1 (plane/pipe index?)
    uint32_t                 _pad_0024;            // +0x24
    void                    *fWriteAccessor;       // +0x28  [VERIFIED] ccont write-accessor
    uint32_t                 mmioAddr_0030;        // +0x30  [VERIFIED] PS_CTRL_2_A  (0x68280) seam scaler
    uint32_t                 mmioAddr_0034;        // +0x34  [VERIFIED] PS_WIN_POS_2_A (0x68270)
    uint32_t                 mmioAddr_0038;        // +0x38  [VERIFIED] PS_WIN_SZ_2_A  (0x68274)
    uint32_t                 mmioAddr_003C;        // +0x3C  [VERIFIED] BCLRPAT_A (0x60020)
    uint8_t                  _opaque[0x118];       // +0x40..+0x157  remainder unverified
};
static_assert(__builtin_offsetof(AppleIntelPlaneRegCache, fWriteAccessor) == 0x28, "AppleIntelPlaneRegCache.fWriteAccessor");
static_assert(__builtin_offsetof(AppleIntelPlaneRegCache, mmioAddr_0030)  == 0x30, "AppleIntelPlaneRegCache.mmioAddr_0030");
static_assert(__builtin_offsetof(AppleIntelPlaneRegCache, mmioAddr_0038)  == 0x38, "AppleIntelPlaneRegCache.mmioAddr_0038");

// struct AppleIntelScalerRegCache — shadow copy of pipe-scaler registers.
// Mirrors the logical SCALERPARAMS register triplet used by setupPipeScaler /
// programPipeScaler.
struct AppleIntelScalerRegCache {
    uint32_t       PS_CTRL;                        // +0x00 [KNOWN] pipe-scaler control
    uint32_t       PS_WIN_POS;                     // +0x04 [KNOWN] scaler window position
    uint32_t       PS_WIN_SZ;                      // +0x08 [KNOWN] scaler window size
};
static_assert(__builtin_offsetof(AppleIntelScalerRegCache, PS_CTRL)   == 0x00, "AppleIntelScalerRegCache.PS_CTRL");
static_assert(__builtin_offsetof(AppleIntelScalerRegCache, PS_WIN_POS) == 0x04, "AppleIntelScalerRegCache.PS_WIN_POS");
static_assert(__builtin_offsetof(AppleIntelScalerRegCache, PS_WIN_SZ)  == 0x08, "AppleIntelScalerRegCache.PS_WIN_SZ");

// struct LinkConfig -- 0x80 bytes (opaque placeholder; actual size TBD)
struct LinkConfig {
    uint8_t        _opaque[128];         // +0x0
};
static_assert(sizeof(LinkConfig) == 0x80, "LinkConfig size");

// ---------------------------------------------------------------------------
// Apple C++ driver objects — partial layouts from PCode analysis + disasm
//
// These are C++ instances (IOService subclass hierarchy). Only ivars that are
// directly accessed in our hooks or needed for getMember<T> calls are named;
// all gaps are opaque padding.  Offsets marked [PCODE] were found by the
// extract_apple_params.py PCode walker; [KNOWN] are from manual disasm and
// are verified against IDA / Ghidra; [ESTIMATED] are inferred from vtable
// size or sibling-class comparison and have NOT been confirmed in binary.
//
// Usage pattern in hooks (never dereference the object through its vtable):
//   auto *ctrl = getMember<AppleIntelBaseController *>(that, 0x00);
//   auto *mmio = getMember<void *>(ctrl, offsetof(AppleIntelBaseController, fMMIO));
// ---------------------------------------------------------------------------

struct AppleIntelBaseController; // forward — defined below

// struct AppleIntelPowerWell — layout from Ghidra decomp of AppleIntelPowerWell::init (TGL kext).
// Registers read during init: 0x45404 (PG), 0x45454 (DDI), 0x45444 (AUX).
// Each fPG/fDDI/fAUX slot is 1 = enabled, 2 = overridden (always-on), 0 = disabled.
//
// init() sets fAlwaysOn = 1 ONLY if fController->flags_ig & FB_FLAG_BOOST_PIXEL_FREQUENCY_LIMIT.
// If that flag isn't set before PowerWell::init runs, fAlwaysOn stays 0 → power wells can be
// gated off at runtime. Our hook forces fAlwaysOn = 1 unconditionally on non-real-TGL hardware.
struct AppleIntelPowerWell {
    uint8_t             _pad_0000[0x10];    // +0x00..+0x0F  vtable + padding
    AppleIntelBaseController *fController;  // +0x10  [KNOWN] (Ghidra: "contr")
    uint8_t             fAlwaysOn;          // +0x18  [KNOWN] (Ghidra: "powerwellalwaysON") 1 = overridePowerWellsState locks wells always-on
    uint8_t             _pad_0019[3];       // +0x19..+0x1B  alignment
    uint32_t            fPGBase;            // +0x1C  base PG (always 1 after init)
    uint32_t            fPG1;              // +0x20  PG1 state  (reg 0x45404 bit 0)
    uint32_t            fPG2;              // +0x24  PG2 state  (reg 0x45404 bit 2)
    uint32_t            fPG3;              // +0x28  PG3 state  (reg 0x45404 bit 4)
    uint32_t            fPG4;              // +0x2C  PG4 state  (reg 0x45404 bit 6)
    uint32_t            fDDI[9];           // +0x30..+0x53  DDI A/B/C/TC1-TC6  (reg 0x45454)
    uint32_t            fAUX[9];           // +0x54..+0x77  AUX A/B/C/TBT1-TBT6 (reg 0x45444)
    AppleIntelMMIO     *fMMIO;             // +0x78  MMIO accessor — set by Apple's init; pass to raReadRegister32, not the PowerWell itself
};
static_assert(__builtin_offsetof(AppleIntelPowerWell, fAlwaysOn)  == 0x18, "AppleIntelPowerWell.fAlwaysOn");
static_assert(__builtin_offsetof(AppleIntelPowerWell, fPGBase)    == 0x1C, "AppleIntelPowerWell.fPGBase");
static_assert(__builtin_offsetof(AppleIntelPowerWell, fDDI)       == 0x30, "AppleIntelPowerWell.fDDI");
static_assert(__builtin_offsetof(AppleIntelPowerWell, fAUX)       == 0x54, "AppleIntelPowerWell.fAUX");
static_assert(__builtin_offsetof(AppleIntelPowerWell, fMMIO)      == 0x78, "AppleIntelPowerWell.fMMIO");

// struct AppleIntelBaseController -- PCode-discovered from AppleIntelBaseController::init, 21 access sites, ~0x1B28 bytes
struct AppleIntelBaseController {
    uint8_t        _pad_0000[0x78]; // +0x0
    AppleIntelMMIO* fMMIO; // +0x78
    uint8_t        _pad_0080[0x898]; // +0x80
    uint32_t       unk_0918; // +0x918
    uint8_t        _pad_091C[0x24C]; // +0x91C
    uint32_t       unk_0B68; // +0xB68
    uint8_t        _pad_0B6C[0x34]; // +0xB6C
    uint32_t       unk_0BA0; // +0xBA0
    uint8_t        _pad_0BA4[0x34]; // +0xBA4
    uint32_t       unk_0BD8;            // +0xBD8
    uint8_t        _pad_0BDC[0x64];    // +0xBDC..+0xC3F
    void          *fRegCachePool;       // +0xC40  [KNOWN] RegCache pool/allocator — captured as ccont in PowerWell::init hook
    uint8_t        _pad_0C48[0x10];    // +0xC48..+0xC57
    uint32_t       flags_ig;           // +0xC58  [KNOWN] boot info flags (Ghidra: "flags_ig"); FB_FLAG_BOOST_PIXEL_FREQUENCY_LIMIT etc. — checked by PowerWell::init to decide fAlwaysOn
    uint32_t       fInfoFlags2;        // +0xC5C  [KNOWN] display feature flags; FB_FLAG_ALTERNATE_PWM_INCREMENT* | FB_FLAG_ENABLE_SLICE_FEATURES etc.
    void          *unk_0C60;           // +0xC60  [DIAG] live pointer observed 0xffffff9060c44280 — identity TBD
    uint8_t        _pad_0C68[0x29C];  // +0xC68..+0xF03
    uint32_t       unk_0F04;            // +0xF04
    uint8_t        _pad_0F08[0x5]; // +0xF08
    uint32_t       unk_0F0D; // +0xF0D
    uint8_t        _pad_0F11[0x193]; // +0xF11
    uint32_t       unk_10A4; // +0x10A4
    uint8_t        _pad_10A8[0x114]; // +0x10A8
    uint32_t       unk_11BC; // +0x11BC
    uint8_t        _pad_11C0[0x20F]; // +0x11C0
    uint32_t       unk_13CF; // +0x13CF
    uint8_t        _pad_13D3[0xDF]; // +0x13D3
    uint32_t       unk_14B2; // +0x14B2
    uint8_t        _pad_14B6[0xA]; // +0x14B6
    uint32_t       unk_14C0; // +0x14C0
    uint8_t        _pad_14C4[0x14]; // +0x14C4
    uint64_t       unk_14D8; // +0x14D8
    uint8_t        _pad_14E0[0x28]; // +0x14E0
    uint64_t       unk_1508; // +0x1508
    uint8_t        _pad_1510[0x31]; // +0x1510
    uint32_t       unk_1541; // +0x1541
    uint8_t        _pad_1545[0xAB]; // +0x1545
    uint32_t       unk_15F0;            // +0x15F0
    uint8_t        _pad_15F4[0x523];   // +0x15F4..+0x1B16  (fGPUIsAwake at +0x1A00 — use getMember; struct not packed)
    uint32_t       unk_1B17; // +0x1B17
    uint8_t        _pad_1B1B[0x5]; // +0x1B1B
    uint32_t       unk_1B20; // +0x1B20
    uint32_t       unk_1B24; // +0x1B24
};
// NOTE: total size is a lower bound; extend once the real sizeof() is known from IDA/Ghidra.
static_assert(__builtin_offsetof(AppleIntelBaseController, fMMIO)       == 0x78,  "AppleIntelBaseController.fMMIO");
static_assert(__builtin_offsetof(AppleIntelBaseController, fRegCachePool) == 0xC40, "AppleIntelBaseController.fRegCachePool");
static_assert(__builtin_offsetof(AppleIntelBaseController, unk_0C60)     == 0xC60, "AppleIntelBaseController.unk_0C60");
static_assert(__builtin_offsetof(AppleIntelBaseController, flags_ig)    == 0xC58,  "AppleIntelBaseController.flags_ig");
static_assert(__builtin_offsetof(AppleIntelBaseController, fInfoFlags2) == 0xC5C,  "AppleIntelBaseController.fInfoFlags2");

// struct AppleIntelDisplayPath -- PCode-discovered from AppleIntelDisplayPath::init, ~0x32B0 bytes
// Verified field types:
//   +0x284: uint8_t (byte flag) — confirmed: `cmp byte [rsi+0x284], 0` / `mov byte [rdi+0x284], 1`
//   +0x32A4: uint8_t (byte flag) — confirmed: `cmp byte [rdx+0x32A4], 0` / `mov byte [rdx+0x32A4], 0/1`
// PREVIOUSLY WRONG: both were declared uint32_t (PCode tool used dword-read heuristic).
struct AppleIntelDisplayPath {
    uint8_t        _pad_0000[0x284]; // +0x0..+0x283
    uint8_t        unk_0284;         // +0x284  [VERIFIED] byte flag
    uint8_t        _pad_0285[0x301F]; // +0x285..+0x32A3
    uint8_t        unk_32A4;         // +0x32A4 [VERIFIED] byte flag
    uint8_t        _pad_32A5[0xB];   // trailing (struct ~0x32B0)
};
// NOTE: total size is a lower bound; extend once the real sizeof() is known from IDA/Ghidra.


// struct AppleIntelFramebuffer -- layout verified from AppleIntelFramebuffer::init disasm.
// init(rdi=this[rbx], rsi=ctrl[r15], rdx=pipeIdx[r14d]):
//   [+0x1D0] ← ctrl (AppleIntelBaseController*, 8B) — fController  [VERIFIED]
//   [+0x1D8] ← some byte flag (1B)
//   [+0x1DC] ← pipeIdx (uint32_t, 4B) — fPipeIndex                 [VERIFIED]
// PREVIOUSLY WRONG: fController at +0x1A8 and fPipeIndex at +0x1B0 (those belong to
// other types sharing the kext binary: AppleIntelMEIDriver / CamelliaTcon).
struct AppleIntelFramebuffer {
    uint8_t        _pad_0000[0x1C8];  // +0x0..+0x1C7
    void          *unk_01C8;          // +0x1C8  [DIAG] live pointer observed 0xffffff9060731000 — identity TBD (sibling fb or display path)
    AppleIntelBaseController* fController; // +0x1D0  [VERIFIED]
    uint8_t        fInitFlag;         // +0x1D8  [DIAG] byte flag = 1 after init
    uint8_t        _pad_01D9[0x3];    // +0x1D9..+0x1DB
    uint32_t       fPipeIndex;        // +0x1DC  [VERIFIED]
    uint8_t        _pad_01E0[0x406C]; // +0x1E0..+0x424B
    uint32_t       unk_424C;          // +0x424C
    uint8_t        _pad_4250[0x39];   // +0x4250
    uint32_t       unk_4289;          // +0x4289
    uint8_t        _pad_428D[0x251];  // +0x428D
    uint32_t       unk_44DE;          // +0x44DE
    uint8_t        _pad_44E2[0xCA];   // +0x44E2
    uint32_t       unk_45AC;          // +0x45AC
    uint8_t        _pad_45B0[0x468];  // +0x45B0
    uint32_t       unk_4A18;          // +0x4A18
    uint8_t        _pad_4A1C[0x170];  // +0x4A1C
    uint32_t       unk_4B8C;          // +0x4B8C
};
// NOTE: total size is a lower bound; extend once the real sizeof() is known from IDA/Ghidra.
static_assert(__builtin_offsetof(AppleIntelFramebuffer, unk_01C8)    == 0x1C8, "AppleIntelFramebuffer.unk_01C8");
static_assert(__builtin_offsetof(AppleIntelFramebuffer, fController) == 0x1D0, "AppleIntelFramebuffer.fController");
static_assert(__builtin_offsetof(AppleIntelFramebuffer, fInitFlag)   == 0x1D8, "AppleIntelFramebuffer.fInitFlag");
static_assert(__builtin_offsetof(AppleIntelFramebuffer, fPipeIndex)  == 0x1DC, "AppleIntelFramebuffer.fPipeIndex");

// struct AppleIntelScaler -- layout fully verified from binary disassembly.
// Methods: init, disableScaler, programPipeScaler all confirm these offsets.
// init(rdi=this, rsi=IGScalerID):
//   zeroes [+0x10] (fController), sets [+0x18]=pipe sel, [+0x1c]=IGScalerID, [+0x20]=0, [+0x28]=null
// disableScaler/programPipeScaler: load vtable object from [this+0x28] and call writeReg32.
struct AppleIntelScaler {
    void          *_vtable;                  // +0x00  C++ vtable pointer
    uint8_t        _pad_0008[0x8];           // +0x08..+0x0F  (parent OSObject fields)
    AppleIntelBaseController *fController;   // +0x10  [VERIFIED] controller back-ptr (zeroed in init)
    uint32_t       fPipeScalerSel;           // +0x18  [VERIFIED] pipe-derived sel (0=A, 1=B/TC)
    uint32_t       fScalerIndex;             // +0x1c  [VERIFIED] IGScalerID passed to init
    uint8_t        fEnabled;                 // +0x20  [VERIFIED] byte
    uint8_t        _pad_0021[0x7];           // +0x21..+0x27
    void          *fWriteAccessor;           // +0x28  [VERIFIED] ccont write-accessor (vtable obj for writeReg32)
    uint32_t       mmioAddr_0030;            // +0x30  PS_CTRL MMIO address
    uint32_t       mmioAddr_0034;            // +0x34  PS_WIN_POS MMIO address
    uint32_t       mmioAddr_0038;            // +0x38  PS_WIN_SZ MMIO address
    uint32_t       mmioAddr_003C;            // +0x3C  BCLRPAT_A (0x60020) — pipe border/bg color
    uint32_t       mmioAddr_0040;            // +0x40  PS_HPHASE MMIO address
    uint32_t       shadow_0044;              // +0x44  [VERIFIED] PS_CTRL shadow (0x200 = ENABLE)
    uint32_t       shadow_0048;              // +0x48  [VERIFIED] PS_WIN_POS shadow
    uint32_t       shadow_004C;              // +0x4C  [VERIFIED] PS_WIN_SZ shadow
    uint32_t       shadow_0050;              // +0x50  [VERIFIED] PS_HPHASE shadow (mmioAddr_0040=0x68194)
    uint32_t       shadow_0054;              // +0x54  unknown (no direct mmioAddr pair)
};
static_assert(__builtin_offsetof(AppleIntelScaler, fController)    == 0x10, "AppleIntelScaler.fController");
static_assert(__builtin_offsetof(AppleIntelScaler, fPipeScalerSel) == 0x18, "AppleIntelScaler.fPipeScalerSel");
static_assert(__builtin_offsetof(AppleIntelScaler, fScalerIndex)   == 0x1c, "AppleIntelScaler.fScalerIndex");
static_assert(__builtin_offsetof(AppleIntelScaler, fEnabled)       == 0x20, "AppleIntelScaler.fEnabled");
static_assert(__builtin_offsetof(AppleIntelScaler, fWriteAccessor) == 0x28, "AppleIntelScaler.fWriteAccessor");

// struct AppleIntelPlane -- layout fully verified from binary disassembly.
// Methods: enablePlane, setupPlane, updateRegisterCache, configurePlane, disablePlane, updatePlane.
//
// Verified key offsets:
//   [+0x68] fController (enablePlane: movq 0x68(%rbx),%rdi — passes to controller methods)
//   [+0x70] fPath       (setupPlane: movq 0x70(%rbx),%rsi — setupPlaneWatermarks arg)
//   [+0x78] fPipeIdx_inline = IGPlaneID/5     [+0x7c] fIGPlaneID = raw IGPlaneID
//   [+0x80] fPlaneIdx_inline = IGPlaneID%5    [+0x84] fEnabled (BYTE)
//   [+0x88] fRegCache   [+0x90] fWriteAccessor (ccont vtable obj for writeReg32)
//   [+0x100] PLANE_CTL  [+0x104] PLANE_STRIDE  [+0x154] PLANE_COLOR_CTL (inline shadows)
//
// ccont MUST go into fWriteAccessor (+0x90) via getMember — NOT fRegCache (+0x88).
// Apple sets fRegCache via allocatePlane as a DSB accessor; overwriting it hangs the boot.
struct AppleIntelPlane {
    void                    *_vtable;              // +0x00  C++ vtable pointer
    uint8_t                  _pad_0008[0x3a];      // +0x08..+0x41  (parent OSObject/IOObject fields)
    uint8_t                  fFlag_0042;           // +0x42  bool flag (cmpb $0x1 in setupPlane)
    uint8_t                  _pad_0043[0x25];      // +0x43..+0x67
    AppleIntelBaseController *fController;          // +0x68  [VERIFIED] controller back-ptr
    AppleIntelDisplayPath    *fPath;                // +0x70  [VERIFIED] display path ptr
    uint32_t                  fPipeIdx_inline;      // +0x78  [VERIFIED] IGPlaneID/5 (pipe index)
    uint32_t                  fIGPlaneID;           // +0x7c  [VERIFIED] raw absolute plane ID
    uint32_t                  fPlaneIdx_inline;     // +0x80  [VERIFIED] IGPlaneID%5 (plane within pipe)
    uint8_t                   fEnabled;             // +0x84  [VERIFIED] byte
    uint8_t                   _pad_0085[0x3];       // +0x85..+0x87
    AppleIntelPlaneRegCache  *fRegCache;            // +0x88  [VERIFIED] — DO NOT write ccont here
    void                    *fWriteAccessor;        // +0x90  [VERIFIED] ccont slot; use getMember to write
    uint32_t                  mmioAddr_PLANE_CTL;   // +0x98  [VERIFIED] PLANE_CTL_1_A (0x70180)
    uint32_t                  mmioAddr_00_9C;       // +0x9C  [UNCONFIRMED] observed 0x701CC — not confirmed as PLANE_STRIDE (see mmioAddr_00B0); may be PLANE_COLOR_CTL or AUX stride
    uint8_t                   _pad_00A0[0x8];       // +0xA0..+0xA7
    uint32_t                  mmioAddr_00A8;        // +0xA8  shadow pair → +0x110
    uint32_t                  mmioAddr_00AC;        // +0xAC  shadow pair → +0x114
    uint32_t                  mmioAddr_PLANE_STRIDE_1A; // +0xB0  [VERIFIED] PLANE_STRIDE_1_A (0x70188); shadow_0118=0x14 = Y-tiled stride for 2560-wide
    uint32_t                  mmioAddr_PLANE_SIZE;  // +0xB4  [VERIFIED] PLANE_SIZE_1_A (0x70190); shadow_011C=0x63f09ff = 2560×1600
    uint32_t                  mmioAddr_00B8;        // +0xB8  PLANE_SURF_1_A (0x7019C); shadow → +0x14C (write adds +0x500)
    uint32_t                  mmioAddr_00BC;        // +0xBC  shadow pair → +0x124
    uint8_t                   _pad_00C0[0x38];      // +0xC0..+0xF7
    uint32_t                  mmioAddr_00F8;        // +0xF8  shadow pair → +0x128
    uint8_t                   _pad_00FC[0x4];       // +0xFC..+0xFF
    uint32_t                  PLANE_CTL;            // +0x100 [VERIFIED] inline shadow
    uint32_t                  PLANE_STRIDE;         // +0x104 [VERIFIED] inline shadow
    uint8_t                   _pad_0108[0x8];       // +0x108..+0x10F
    uint32_t                  shadow_0110;          // +0x110 shadow for mmioAddr_00A8
    uint32_t                  shadow_0114;          // +0x114 shadow for mmioAddr_00AC
    uint32_t                  shadow_PLANE_STRIDE;  // +0x118 [VERIFIED] PLANE_STRIDE shadow; observed 0x14 (Y-tiled stride for 2560-wide)
    uint32_t                  shadow_PLANE_SIZE;    // +0x11C [VERIFIED] PLANE_SIZE shadow; observed 0x63f09ff = 2560×1600
    uint32_t                  shadow_0120;          // +0x120 unknown
    uint32_t                  shadow_0124;          // +0x124 shadow for mmioAddr_00BC
    uint32_t                  shadow_0128;          // +0x128 shadow for mmioAddr_00F8
    uint8_t                   _pad_012C[0x20];      // +0x12C..+0x14B
    uint32_t                  shadow_014C;          // +0x14C cursor shadow for mmioAddr_00B8
    uint32_t                  shadow_0150;          // +0x150
    uint32_t                  PLANE_COLOR_CTL;      // +0x154 [VERIFIED] inline shadow
    uint8_t                   _pad_0158[0x48];      // +0x158..+0x19F
};
static_assert(__builtin_offsetof(AppleIntelPlane, fController)           == 0x68,  "AppleIntelPlane.fController");
static_assert(__builtin_offsetof(AppleIntelPlane, fPath)                 == 0x70,  "AppleIntelPlane.fPath");
static_assert(__builtin_offsetof(AppleIntelPlane, fPipeIdx_inline)       == 0x78,  "AppleIntelPlane.fPipeIdx_inline");
static_assert(__builtin_offsetof(AppleIntelPlane, fIGPlaneID)            == 0x7C,  "AppleIntelPlane.fIGPlaneID");
static_assert(__builtin_offsetof(AppleIntelPlane, fPlaneIdx_inline)      == 0x80,  "AppleIntelPlane.fPlaneIdx_inline");
static_assert(__builtin_offsetof(AppleIntelPlane, fEnabled)              == 0x84,  "AppleIntelPlane.fEnabled");
static_assert(__builtin_offsetof(AppleIntelPlane, fRegCache)             == 0x88,  "AppleIntelPlane.fRegCache");
static_assert(__builtin_offsetof(AppleIntelPlane, fWriteAccessor)        == 0x90,  "AppleIntelPlane.fWriteAccessor");
static_assert(__builtin_offsetof(AppleIntelPlane, mmioAddr_PLANE_CTL)    == 0x98,  "AppleIntelPlane.mmioAddr_PLANE_CTL");
static_assert(__builtin_offsetof(AppleIntelPlane, mmioAddr_00_9C)              == 0x9C,  "AppleIntelPlane.mmioAddr_00_9C");
static_assert(__builtin_offsetof(AppleIntelPlane, mmioAddr_PLANE_STRIDE_1A)    == 0xB0,  "AppleIntelPlane.mmioAddr_PLANE_STRIDE_1A");
static_assert(__builtin_offsetof(AppleIntelPlane, mmioAddr_PLANE_SIZE)         == 0xB4,  "AppleIntelPlane.mmioAddr_PLANE_SIZE");
static_assert(__builtin_offsetof(AppleIntelPlane, PLANE_CTL)             == 0x100, "AppleIntelPlane.PLANE_CTL");
static_assert(__builtin_offsetof(AppleIntelPlane, PLANE_STRIDE)          == 0x104, "AppleIntelPlane.PLANE_STRIDE");
static_assert(__builtin_offsetof(AppleIntelPlane, PLANE_COLOR_CTL)       == 0x154, "AppleIntelPlane.PLANE_COLOR_CTL");

// struct FlipTransactionArgs -- verified from configurePlane disasm (r15=this).
// +0xC..+0x28: ALL float (cvttss2si — rect coordinates, x/y/w/h pairs)
// +0x1C was WRONG as BPCSelector — it is a float rect coordinate.
// BPC is read from PIPE_MISC hardware register [5:3], not from this struct.
struct FlipTransactionArgs {
    uint32_t       unk_0000;          // +0x0
    uint8_t        _pad_0004[0x4];    // +0x4..+0x7
    uint32_t       unk_0008;          // +0x8
    float          flt_000C;          // +0xC   [VERIFIED float]
    float          flt_0010;          // +0x10  [VERIFIED float]
    float          flt_0014;          // +0x14  [VERIFIED float]
    float          flt_0018;          // +0x18  [VERIFIED float]
    float          flt_001C;          // +0x1C  [VERIFIED float] — was WRONG as BPCSelector
    float          flt_0020;          // +0x20  [VERIFIED float]
    float          flt_0024;          // +0x24  [VERIFIED float]
    float          flt_0028;          // +0x28  [VERIFIED float]
    uint32_t       unk_002C;          // +0x2C  bitmask (bits 0,2,4 tested)
    uint8_t        unk_0030;          // +0x30  byte
    uint8_t        unk_0031;          // +0x31  byte
    uint8_t        unk_0032;          // +0x32  byte
    uint8_t        _pad_0033;         // +0x33  alignment
    uint32_t       unk_0034;          // +0x34  format/pixel-type ID
    uint32_t       unk_0038;          // +0x38  enum 0 or 1
    uint32_t       TilingEnum;        // +0x3C  [VERIFIED] tiling: 0=X-tiled, 1=Y-tiled, 2=linear
    uint32_t       unk_0040;          // +0x40
    uint8_t        _pad_0044[0xC];    // +0x44..+0x4F
    uint32_t       unk_0050;          // +0x50
};
// NOTE: total size is a lower bound; extend once the real sizeof() is known from IDA/Ghidra.
static_assert(__builtin_offsetof(FlipTransactionArgs, flt_001C)  == 0x1C, "FlipTransactionArgs.flt_001C");
static_assert(__builtin_offsetof(FlipTransactionArgs, unk_002C)  == 0x2C, "FlipTransactionArgs.unk_002C");
static_assert(__builtin_offsetof(FlipTransactionArgs, unk_0030)  == 0x30, "FlipTransactionArgs.unk_0030");
static_assert(__builtin_offsetof(FlipTransactionArgs, unk_0034)  == 0x34, "FlipTransactionArgs.unk_0034");
static_assert(__builtin_offsetof(FlipTransactionArgs, unk_0038)  == 0x38, "FlipTransactionArgs.unk_0038");
static_assert(__builtin_offsetof(FlipTransactionArgs, TilingEnum) == 0x3C, "FlipTransactionArgs.TilingEnum");
static_assert(__builtin_offsetof(FlipTransactionArgs, unk_0040)  == 0x40, "FlipTransactionArgs.unk_0040");
static_assert(__builtin_offsetof(FlipTransactionArgs, unk_0050)  == 0x50, "FlipTransactionArgs.unk_0050");

//unconsolidated structs.. still needs study..

// ---------------------------------------------------------------------------
// Accelerator / 3D-path structs
// Discovered by tools/extract_apple_params.py PCode analysis of the
// AppleIntelTGLGraphicsAccelerator kext.  Offsets confirmed against
// kern_gen11.cpp hook code and Ghidra decompile of key functions.
// ---------------------------------------------------------------------------

// IntelAccelerator — partial layout, lower-bound size.
// Key topology fields from getGPUInfo/getGPUInfoICL disasm (kern_gen11.cpp).
// IGVector fields (0x12C0..0x12D8) from Ghidra populateResetRegisterList decompile.
// fMMIOBase (0x1240) confirmed via *(long *)(this + 0x1240) in populateResetRegisterList.
struct IntelAccelerator {
    uint8_t        _pad_0000[0xC78];       // +0x0
    uint32_t       unk_0C78;               // +0xC78
    uint8_t        _pad_0C7C[0x15C];       // +0xC7C
    uint32_t       fNumSlicesMirror;       // +0xDD8  (TGL getGPUInfo mirror)
    uint32_t       fNumSubSlicesMirror;    // +0xDDC  (TGL getGPUInfo mirror)
    uint8_t        _pad_0DE0[0x344];       // +0xDE0..+0x1123  (opaque; contains embedded sub-structs at +0xF10/+0xF2E/+0xFED confirmed via leaq/movq in initHardwareWorkarounds)
    uint32_t       fExecutionUnitCount;    // +0x1124 (MaxEU × NumSubSlices)
    uint8_t        _pad_1128[0x28];        // +0x1128
    uint64_t       fFrequencyPair;         // +0x1150 (lo=fMaxMHz, hi=fMinMHz)
    uint32_t       fNumSubSlices;          // +0x1158
    uint32_t       fNumSlices;             // +0x115C
    uint8_t        _pad_1160[0x4];         // +0x1160
    uint32_t       fL3BankCount;           // +0x1164
    uint8_t        _pad_1168[0x4];         // +0x1168
    uint32_t       fMaxEUPerSubSlice;      // +0x116C
    uint8_t        _pad_1170[0x18];        // +0x1170
    uint32_t       unk_1188;               // +0x1188  (movl in getGPUInfo — g_timestampFreqPerDenominator-related)
    uint8_t        _pad_118C[0x4];         // +0x118C
    uint64_t       unk_1190;               // +0x1190  (qword: NumSlices-derived bitmask, movq in getGPUInfo)
    uint8_t        _pad_1198[0x90];        // +0x1198
    uint64_t       unk_1228;               // +0x1228
    uint8_t        _pad_1230[0x10];        // +0x1230
    volatile uint8_t *fMMIOBase;           // +0x1240  MMIO BAR0 mapping
    uint8_t        _pad_1248[0x44];        // +0x1248
    uint8_t        fbRegistered;           // +0x128C  set by registerWithFramebufferController
    uint8_t        _pad_128D[0xF];         // +0x128D
    uint32_t       unk_129C;               // +0x129C
    uint8_t        _pad_12A0[0x20];        // +0x12A0
    uint64_t       fResetRegCount;         // +0x12C0  IGVector.count
    uint64_t       fResetRegCapacity;      // +0x12C8  IGVector.capacity
    void          *fResetRegData;          // +0x12D0  IGVector.data (0x24-byte entries)
    uint8_t        _pad_12D8[0x28];        // +0x12D8
    uint32_t       unk_1300;               // +0x1300
    uint8_t        _pad_1304[0x170];       // +0x1304
    uint32_t       unk_1474;               // +0x1474
    uint8_t        _pad_1478[0x7DC];       // +0x1478
    uint32_t       unk_1C54;               // +0x1C54
};
// NOTE: total size is a lower bound.
static_assert(__builtin_offsetof(IntelAccelerator, fNumSlicesMirror)    == 0xDD8,  "IntelAccelerator.fNumSlicesMirror");
static_assert(__builtin_offsetof(IntelAccelerator, fNumSubSlicesMirror) == 0xDDC,  "IntelAccelerator.fNumSubSlicesMirror");
static_assert(__builtin_offsetof(IntelAccelerator, fExecutionUnitCount) == 0x1124, "IntelAccelerator.fExecutionUnitCount");
static_assert(__builtin_offsetof(IntelAccelerator, fFrequencyPair)      == 0x1150, "IntelAccelerator.fFrequencyPair");
static_assert(__builtin_offsetof(IntelAccelerator, fNumSubSlices)       == 0x1158, "IntelAccelerator.fNumSubSlices");
static_assert(__builtin_offsetof(IntelAccelerator, fNumSlices)          == 0x115C, "IntelAccelerator.fNumSlices");
static_assert(__builtin_offsetof(IntelAccelerator, fL3BankCount)        == 0x1164, "IntelAccelerator.fL3BankCount");
static_assert(__builtin_offsetof(IntelAccelerator, fMaxEUPerSubSlice)   == 0x116C, "IntelAccelerator.fMaxEUPerSubSlice");
static_assert(__builtin_offsetof(IntelAccelerator, unk_1188)            == 0x1188, "IntelAccelerator.unk_1188");
static_assert(__builtin_offsetof(IntelAccelerator, unk_1190)            == 0x1190, "IntelAccelerator.unk_1190");
static_assert(__builtin_offsetof(IntelAccelerator, fMMIOBase)           == 0x1240, "IntelAccelerator.fMMIOBase");
static_assert(__builtin_offsetof(IntelAccelerator, fbRegistered)        == 0x128C, "IntelAccelerator.fbRegistered");
static_assert(__builtin_offsetof(IntelAccelerator, fResetRegCount)      == 0x12C0, "IntelAccelerator.fResetRegCount");
static_assert(__builtin_offsetof(IntelAccelerator, fResetRegCapacity)   == 0x12C8, "IntelAccelerator.fResetRegCapacity");
static_assert(__builtin_offsetof(IntelAccelerator, fResetRegData)       == 0x12D0, "IntelAccelerator.fResetRegData");

// IGAccelTask context slots confirmed from the Tahoe TGL getters at
// 0x80ae/0x8114/0x817a/0x81f6. initWithOptions clears all four and release
// independently notifies/releases them; they are distinct owned objects.
struct IGAccelTask {
    uint8_t        _pad_0000[0x290];       // +0x0
    void          *fBlit2DContext;         // +0x290  IGHardwareBlit2DContext*
    void          *fBlit3DContext;         // +0x298  IGHardwareBlit3DContext*
    void          *fDepthResolveContext;   // +0x2A0  IGHardwareResolveContext*
    void          *fColorResolveContext;   // +0x2A8  IGHardwareResolveContext*
};
// NOTE: total size is a lower bound.
static_assert(__builtin_offsetof(IGAccelTask, fBlit2DContext)       == 0x290, "IGAccelTask.fBlit2DContext");
static_assert(__builtin_offsetof(IGAccelTask, fBlit3DContext)       == 0x298, "IGAccelTask.fBlit3DContext");
static_assert(__builtin_offsetof(IGAccelTask, fDepthResolveContext) == 0x2A0, "IGAccelTask.fDepthResolveContext");
static_assert(__builtin_offsetof(IGAccelTask, fColorResolveContext) == 0x2A8, "IGAccelTask.fColorResolveContext");

// IGHardwareBlit3DContext — vtable confirmed; unk_0112 from blit3d_init_ctx disasm
// (movb $0x0, 0x112(%rdi) — byte, NOT uint32_t; total struct size = 0x118 from MetaClass).
struct IGHardwareBlit3DContext {
    void          *vtable;                 // +0x0
    uint8_t        _pad_0008[0x10A];       // +0x8
    uint8_t        unk_0112;               // +0x112  bool/byte (movb $0x0 in blit3d_init_ctx)
};
// NOTE: total size is a lower bound.
static_assert(__builtin_offsetof(IGHardwareBlit3DContext, vtable)   == 0x0,   "IGHardwareBlit3DContext.vtable");
static_assert(__builtin_offsetof(IGHardwareBlit3DContext, unk_0112) == 0x112, "IGHardwareBlit3DContext.unk_0112");

// IGHardwareExtendedContextParams — unk_000C from PCode of initWithOptions.
struct IGHardwareExtendedContextParams {
    uint8_t        _pad_0000[0xC];         // +0x0
    uint32_t       unk_000C;               // +0xC
};
// NOTE: total size is a lower bound.

// blit3d_params_t — 4 fields from PCode of IntelAccelerator::submitBlit.
// unk_00A0 confirmed as byte: movzbl 0xa0(%r12) + movb $0x1, 0xa0(%r12) in blit3d_submit_commands.
struct blit3d_params_t {
    uint8_t        _pad_0000[0x3C];        // +0x0
    uint32_t       unk_003C;               // +0x3C
    uint8_t        _pad_0040[0x44];        // +0x40
    uint32_t       unk_0084;               // +0x84
    uint8_t        _pad_0088[0x18];        // +0x88
    uint8_t        unk_00A0;               // +0xA0  byte (movzbl/movb in blit3d_submit_commands)
    uint8_t        _pad_00A1[0x17];        // +0xA1
    uint32_t       unk_00B8;               // +0xB8
};
// NOTE: total size is a lower bound.

// IGAccelSegmentResourceList — fields from markBlitUsage/initBlitUsage disasm.
// Binary evidence: setne 0x78(%rbx) / setne 0x79(%rbx) — both are bools.
// +0x68 = IGAccelTask* (movq 0x68(%rdi)); +0x70/+0x74 = saved context stamps (uint32_t).
struct IGAccelSegmentResourceList {
    uint8_t        _pad_0000[0x68];        // +0x0
    void          *fTask;                  // +0x68  IGAccelTask* (used by initBlitUsage/markBlitUsage)
    uint32_t       unk_0070;               // +0x70  saved blit2D context stamp
    uint32_t       unk_0074;               // +0x74  saved blit3D context stamp
    uint8_t        unk_0078;               // +0x78  bool: blit2D context changed (setne in markBlitUsage)
    uint8_t        unk_0079;               // +0x79  bool: blit3D context changed (setne in markBlitUsage)
};
// NOTE: total size is a lower bound.
static_assert(__builtin_offsetof(IGAccelSegmentResourceList, fTask)    == 0x68, "IGAccelSegmentResourceList.fTask");
static_assert(__builtin_offsetof(IGAccelSegmentResourceList, unk_0070) == 0x70, "IGAccelSegmentResourceList.unk_0070");
static_assert(__builtin_offsetof(IGAccelSegmentResourceList, unk_0074) == 0x74, "IGAccelSegmentResourceList.unk_0074");
static_assert(__builtin_offsetof(IGAccelSegmentResourceList, unk_0078) == 0x78, "IGAccelSegmentResourceList.unk_0078");
static_assert(__builtin_offsetof(IGAccelSegmentResourceList, unk_0079) == 0x79, "IGAccelSegmentResourceList.unk_0079");

// IGAccelSysMemory — opaque; wire/unwire/getPhysicalSegment PCode yielded no
// constant-offset this-pointer accesses.  Define fields in Ghidra manually.
struct IGAccelSysMemory {
    uint8_t        _opaque[1];
};

} // namespace AppleIntel

#endif // AppleIntelParams_hpp
